### ISSUE TITLE
Port 8080 in use error in AWS ECS FARGATE

### ISSUE THREAD

**Issue by vishallanke** [reportportal/service-index#13]
I am retying to hosted report portal in AWS FARGATE ECS. Postgres is hosted inside AWS RDS. I have created Cluster. Then, created Task Definition. All the containers like gateway, index, ui, api, minio, rabbitmq are added in containers. Create task and start it.

Services created above gets started. For index, I am getting error as Port 8080 in use.

Is it because of Gateway container in same task definition ?

Is there a way to change Port for Index service ?

Note - If I create task definition and add only index containers ( no other container), then it works

**Comment by avarabyeu** [comment]
There is env variable that you can use to pass another port: `RP_SERVER_PORT`
